apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nats-helm.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nats-helm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nats-helm.name" . }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: nats
          image: {{ .Values.image }}
          args: ["-DV"]
          ports:
            - name: client
              containerPort: 4222
          securityContext:
            allowPrivilegeEscalation: false
          resources:
{{- toYaml .Values.resources | nindent 12 }}
