apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats-helm.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "nats-helm.name" . }}
  ports:
    - name: client
      port: {{ .Values.service.port }}
      targetPort: 4222
